### ISSUE TITLE
Future updates

### ISSUE THREAD

**Issue by HenryQuan** [HenryQuan/AnimeOne#1]
*I am working on other projects*

# Version 1.1.0
- [ ] solve IOS rotation issue (low priority)
- [ ] Last watched episode
- [ ] Remember watch history (put a tick somewhere so that users could tick it after watching it)
- [ ] choose if internal video player should be used
- [ ] Multiple languages? (But update message will always be in Chinese)
- [ ] Bookmark?
- [x] Update GitHub screenshot
- [x] Better README
- [ ] Privacy policy -> popup

if you don't use this app for a while, it is indeed hard to know which episodes you have watched. Therefore, this update should be a major update 1.1.0, not 1.0.7

# UWP version
It seems possible to port electron apps to uwp. It will definitely be better than AnimeGo. I need to spend sometime fixing its design and remove ads if possible.

# Version 1.0.8
- [x] Update version check
- [x] Force data to update when a new version has been installed
- [x] Don't follow system dark mode as it breaks the bottom bar
- [x] Better dark mode navigation bar brightness
- [x] Fix could not load error
- [x] Get cookies from native webview for Android
- [x] Restart app with native code
- [x] Pink startup screen (black now)
- [x] Go to support page from latest
- [x] Double tap to adjust video speed (but there are no feedback now)
- [x] Resolve cookie issue once for all
- [x] Age restriction due to some Isekai anime (show a popup alert)
- [x] User can enter password so resolve password issue
- [x] Refreshed Android icons (it is fine)
- [x] ~~Slightly different UI for larger devices~~ Maybe later

Some are not implemented and I will leave them in future updates.

### Desktop 0.0.1
Currently, an early version has been released. I am quite surprised at how well it works. Unfortunately, webview is not supported yet. Desktop version is merely web version with electron. There need to be some optimizations for it.

- [x] Longer timeout delay
- [x] Remove/hide menu
- [x] Icon (kinda)
- [x] Fixed windows size
- [x] Dynamic background colour to reduce the lag
- [ ] Share -> Copy link

#### Web
It wasn't working due to cors policy and a backend server is necessary. It won't be hard to get a backend server running but probably not.

# Version 1.0.7
- [X] ~~Add Cookie to API?~~ Alternative solution has been found
- [x] ~~check for update algorithm update (support 1.0.10+ now 1.0.10 is not an update compared to 1.0.9, also avoid 1.0.10, maybe just check if it is different?)~~ I will avoid 1.0.10 because it is just not my style
- [x] Add some dynamic filters to filter 4 seasons
- [x] When there are no entries, show some messages
- [x] Dark mode should be from 6pm to 6am
- [x] ~~Add search button next to new release (reuse schedule cell)~~ maybe later...?
- [x] When loading failed and refresh. Make sure you clear loaded data to prevent duplicates
- [x] Upgrade to Flutter 1.12 (now uses Swift and Kotlin)

# Version 1.0.6
- [x] ~~Better TV support~~ it seems that it doesn't support it yet
- [x] YouTube video will still use browser
- [x] Add a check for update button when app failed to load
- [x] Show alert before the user wants to send me an email
- [x] Allow user to use ~~in app webview~~ browser to use anime1 website
- [x] Fix check for update description
- [x] full screen mode in video
- [x] make player full screen by default in video
- [x] ~~fix ios rotation issue (it only works for Android)~~ maybe in the next version
- [x] close button for iOS
- [x] better watching experience

# Version 1.0.5
- [x] Change play button colour to pink
- [x] Check for update inside settings
- [x] Add privacy policy inside settings
- [x] ~~Better tablet support~~ maybe later
- [x] Enhanced post date
- [x] ~~Fix videos with password~~ It is gone for now
- [x] Play all videos in app
- [x] auto landscape

# Version 1.0.4
- [x] Better error prevention (like sending email, ~~use [catcher](https://github.com/jhomlala/catcher)??~~ later maybe)
- [x] Use app logo other than info icon (need some polish)
- [x] Round button for seasonal anime (it looks kinda off)
- [x] ~~Bypass checking for browser~~ Add message
- [x] Send email button
- [x] Force data update tomorrow (update last update date to today - 6)
- [x] Fix seasonal anime
- [x] Remove please recompile for Android
- [x] SafeArea for iPhone X
- [x] Everything doesn't load (fixed but not tested yet)
- [x] ~~Release ipa file and setup altstore?~~ Maybe 1.0.5

# Version 1.0.3
- [x] Optional parameter to indicate whether Anime shows all episodes
- [x] Add filter buttons under the search field for quick filter (ova, airing, movie and so on...)
- [x] Think about design
- [x] Force update data in app (is it necessary???)
- [x] Better accessibility (add more tooltips)
- [x] Change the colour of about button (it is not visible in light mode)
- [x] Update video playback failure message (the video is broken)
- [x] Remove unnecessary icons
- [x] Cover images will scale up if too small
- [x] Rename AnimeParser to something like BasicParser (GitHub update is not related to Anime)

# Version 1.0.2
- [x] Wait for the new season (everything ready)
- [x] Force update on 1st Jan/Apr/July/Oct
- [x] Share app inside About
- [x] Add Patreon and PayPal inside the app
- [x] Fix video playback (it is fine)
- [x] Use list.generate [here](https://github.com/HenryQuan/AnimeOne/blob/ffed560c81882505ff056e6d74bcdaef67beaaf4/animeone/lib/core/GlobalData.dart#L101) or not?
- [x] Check for update should be different on IOS (like please recompile?)
- [x] Update popup will not be dismissible

# Version 1.0.1
- [x] Update navbar theme colour (black for dark theme and white for light theme)
- [x] Follow system dark mode
- [x] Data are updated too often, just one extra line [here](https://github.com/HenryQuan/AnimeOne/blob/ffed560c81882505ff056e6d74bcdaef67beaaf4/animeone/lib/core/GlobalData.dart#L83)
- [x] Update to flutter 1.9

# Version 1.0.0
- [x] Add a logo for Android and IOS
- [x] Setup Android project in Android Studio
- [x] Setup IOS project in Xcode
- [x] ~~Use [catcher](https://github.com/jhomlala/catcher) to catch error and display it nicely~~ Maybe later
- [x] ~~Add tablet layout for schedule~~ It is fine with the new layout
- [x] Better layout for schedule
- [x] Fix bottom navigation (don't reload when tab switches)
- [X] Only update schedule once a week
- [x] Check for update once a week
- [x] Update anime list once a ~~day~~ week
- [x] Remove all episodes and next episode button when the list has more than one item
- [x] Add a new tab to get the latest anime (only 10 of them, 留言板)
- [x] Better data loading screen
- [x] Cache some data locally
- [x] Add Settings page and link to anime1
- [x] Update README and link with AnimeGo
- [x] Better search system
- [x] Add some screenshots
- [x] ~~Some Animations?~~ I have tried a little bit but it is good for now
- [x] Use [Chewie](https://github.com/brianegan/chewie) to play videos natively requested by senpai
- [x] Auto dark mode
- [x] Add license notice
- [x] Parse video link in video page (source tag or file:"(.*?.mp4.*?)")

# Bugs
- [x] Invalid arguments (there seems to be some errors with new season)
- [x] `App crashes when search icon in Anime is pressed.` Everything works fine on IOS except this and this is IOS only. Android does not have the same issue. (It was because of URL encoding)
- [x] Weird rotation issue (it works on my tablet so I have no idea what's going on) I will open an issue for this. This happens only on my device (it is fine now?? What happened?)
- [x] `https://anime1.me/category/2018秋季/關於我轉生變成史萊姆這檔事` won't load due to unknown reason (it was a parsing issue)
- [x] Search crashing randomly (ask user to send me an email if it happens)

# Version 0.0.2
- [x] Add a button inside video page to open in browser
- [x] Make the background black in the video page
- [x] Better loading animation for anime page

# Version 0.0.3
- [x] Use LinearProgressBar instead
- [x] Move episode tag in front
- [x] Add refresh icon to load recent anime

# Version 0.0.4
- [x] ~~Add last watched episode (save Anime page)~~ Maybe later

Never know how long this app gonna work...

**Comment by tyfu86** [comment]
> # Version 1.0.6
> * [ ]  Better tablet support
> * [ ]  Add a check for update button when app failed to load
> * [ ]  Allow user to use in app webview to browse anime1 website (need to check if the experience is great or not)
> * [ ]  Fix check for update description
> * [x]  full screen mode in video
> * [x]  make player full screen by default in video
> * [ ]  fix ios rotation issue (it only works for Android)
> * [x]  better watching experience
> 
> # Version 1.0.5
> * [x]  Change play button colour to pink
> * [x]  Check for update inside settings
> * [x]  Add privacy policy inside settings
> * [x]  ~Better tablet support~ maybe later
> * [x]  Enhanced post date
> * [x]  ~Fix videos with password~ It is gone for now
> * [x]  Play all videos in app
> * [x]  auto landscape
> 
> # Version 1.0.4
> * [x]  Better error prevention (like sending email, ~use [catcher](https://github.com/jhomlala/catcher)??~ later maybe)
> * [x]  Use app logo other than info icon (need some polish)
> * [x]  Round button for seasonal anime (it looks kinda off)
> * [x]  ~Bypass checking for browser~ Add message
> * [x]  Send email button
> * [x]  Force data update tomorrow (update last update date to today - 6)
> * [x]  Fix seasonal anime
> * [x]  Remove please recompile for Android
> * [x]  SafeArea for iPhone X
> * [x]  Everything doesn't load (fixed but not tested yet)
> * [x]  ~Release ipa file and setup altstore?~ Maybe 1.0.5
> 
> # Version 1.0.3
> * [x]  Optional parameter to indicate whether Anime shows all episodes
> * [x]  Add filter buttons under the search field for quick filter (ova, airing, movie and so on...)
> * [x]  Think about design
> * [x]  Force update data in app (is it necessary???)
> * [x]  Better accessibility (add more tooltips)
> * [x]  Change the colour of about button (it is not visible in light mode)
> * [x]  Update video playback failure message (the video is broken)
> * [x]  Remove unnecessary icons
> * [x]  Cover images will scale up if too small
> * [x]  Rename AnimeParser to something like BasicParser (GitHub update is not related to Anime)
> 
> # Version 1.0.2
> * [x]  Wait for the new season (everything ready)
> * [x]  Force update on 1st Jan/Apr/July/Oct
> * [x]  Share app inside About
> * [x]  Add Patreon and PayPal inside the app
> * [x]  Fix video playback (it is fine)
> * [x]  Use list.generate [here](https://github.com/HenryQuan/AnimeOne/blob/ffed560c81882505ff056e6d74bcdaef67beaaf4/animeone/lib/core/GlobalData.dart#L101) or not?
> * [x]  Check for update should be different on IOS (like please recompile?)
> * [x]  Update popup will not be dismissible
> 
> # Version 1.0.1
> * [x]  Update navbar theme colour (black for dark theme and white for light theme)
> * [x]  Follow system dark mode
> * [x]  Data are updated too often, just one extra line [here](https://github.com/HenryQuan/AnimeOne/blob/ffed560c81882505ff056e6d74bcdaef67beaaf4/animeone/lib/core/GlobalData.dart#L83)
> * [x]  Update to flutter 1.9
> 
> # Version 1.0.0
> * [x]  Add a logo for Android and IOS
> * [x]  Setup Android project in Android Studio
> * [x]  Setup IOS project in Xcode
> * [x]  ~Use [catcher](https://github.com/jhomlala/catcher) to catch error and display it nicely~ Maybe later
> * [x]  ~Add tablet layout for schedule~ It is fine with the new layout
> * [x]  Better layout for schedule
> * [x]  Fix bottom navigation (don't reload when tab switches)
> * [x]  Only update schedule once a week
> * [x]  Check for update once a week
> * [x]  Update anime list once a ~day~ week
> * [x]  Remove all episodes and next episode button when the list has more than one item
> * [x]  Add a new tab to get the latest anime (only 10 of them, 留言板)
> * [x]  Better data loading screen
> * [x]  Cache some data locally
> * [x]  Add Settings page and link to anime1
> * [x]  Update README and link with AnimeGo
> * [x]  Better search system
> * [x]  Add some screenshots
> * [x]  ~Some Animations?~ I have tried a little bit but it is good for now
> * [x]  Use [Chewie](https://github.com/brianegan/chewie) to play videos natively requested by senpai
> * [x]  Auto dark mode
> * [x]  Add license notice
> * [x]  Parse video link in video page (source tag or file:"(._?.mp4._?)")
> 
> # Bugs
> * [x]  Invalid arguments (there seems to be some errors with new season)
> * [x]  `App crashes when search icon in Anime is pressed.` Everything works fine on IOS except this and this is IOS only. Android does not have the same issue. (It was because of URL encoding)
> * [x]  Weird rotation issue (it works on my tablet so I have no idea what's going on) I will open an issue for this. This happens only on my device (it is fine now?? What happened?)
> * [x]  `https://anime1.me/category/2018秋季/關於我轉生變成史萊姆這檔事` won't load due to unknown reason (it was a parsing issue)
> * [x]  Search crashing randomly (ask user to send me an email if it happens)
> 
> # Version 0.0.2
> * [x]  Add a button inside video page to open in browser
> * [x]  Make the background black in the video page
> * [x]  Better loading animation for anime page
> 
> # Version 0.0.3
> * [x]  Use LinearProgressBar instead
> * [x]  Move episode tag in front
> * [x]  Add refresh icon to load recent anime
> 
> # Version 0.0.4
> * [x]  ~Add last watched episode (save Anime page)~ Maybe later
> 
> Never know how long this app gonna work...

**Comment by HenryQuan** [comment]
If you have any issues, please open an issue.
