### ISSUE TITLE
楓林網違反著作權法被抄家Anime1也有機會...

### ISSUE THREAD

**Issue by aunight** [HenryQuan/AnimeOne#10]
https://www.techbang.com/posts/77606-maple-forest-net-was-caught-why-there-is-still-a-cottage-maple-forest-network-exists
完蛋囉~
我是覺得可以轉AGE動漫 可是他站點多片源多但更新速度也不一
像今天更新的噬血狂襲第四季 OVA
 .top的已經更新第二集生肉了
.tv的還沒

**Comment by HenryQuan** [comment]
這個在說吧。雖然幾天就可以開發一個出來，但是我覺得App已經夠用了。因為和開發沒有直接的關係，我就先關閉這個issue了。
