### ISSUE TITLE
1.1.0 - 復活のAnimeOne

### ISSUE THREAD

**Issue by HenryQuan** [HenryQuan/AnimeOne#12]
目前1.0.8版本可以正常使用。

- [x] Update Flutter to the latest version
- [x] Fix video player or not
- [x] Fix time table
- [x] Fix data update issue
- [x] Fix other issues

Next step, null safety migration.

**Comment by HenryQuan** [comment]
更新完畢，可以繼續使用 AnimeOne 了。

**Comment by aunight** [comment]
有ipa版嗎 我轉iOS了

**Comment by HenryQuan** [comment]
有的，但是安裝會很複雜因為App沒有上架AppStore。

**Comment by aunight** [comment]
沒問題 我會安裝 我用sideloadly

**Comment by HenryQuan** [comment]
這樣應該就沒問題了。但是iOS應該更新會慢一點。因為要換電腦才可以生成IPA包。Flutter本身是支持iOS的。

**Comment by aunight** [comment]
好的感謝

**Comment by aunight** [comment]
我剛剛裝了舊版 可以正常使用

**Comment by HenryQuan** [comment]
好的，之後我更新一下iOS版。目前在計畫增加一些新功能。
