### ISSUE TITLE
老平板無法開啟

### ISSUE THREAD

**Issue by leadra** [HenryQuan/AnimeOne#15]
我的馳為hi12
安卓版本5.1
安裝後無法開啟，請問有什麼相容的辦法嗎？

**Comment by HenryQuan** [comment]
是會閃退麼？

**Comment by leadra** [comment]
真不好意思，太少看gmail
基本上開啟，進去全螢幕直接跳出來
訊息寫無法開啟應用

**Comment by HenryQuan** [comment]
沒事沒事，多謝回復。我看了一下，馳為hi12是雙系統Win10和安卓，使用Intel Atom®的芯片。可能是因爲是x86-64的原因所以app閃退了。Flutter好像是不支持x86-64的只可以ARM。

**Comment by leadra** [comment]
原來如此，只好放棄了
age的app也是這樣吧

**Comment by HenryQuan** [comment]
嗯應該把，有些App不支持x86-64。

**Comment by leadra** [comment]
感謝你
以後也不會買這種雙系統的了。
弊病不少
幸好網頁還能用就好
到時來裝盒子看看
