### ISSUE TITLE
Android9播放仍然還是會跳到瀏覽器

### ISSUE THREAD

**Issue by aunight** [HenryQuan/AnimeOne#2]
如題但是新番區的正常

**Comment by HenryQuan** [comment]
这个其实是根据视频源做出的决定。
如果找不到视频的真播放地址，APP就会启动浏览器。

**Comment by aunight** [comment]
那這樣就沒有用APP的意義了啊
希望是都可以APP內播放
因為跳到瀏覽器還要調整手機轉向的問題

**Comment by HenryQuan** [comment]
这个是真的没有办法。可以的话，可以提供一下视频链接么。
其实并不是没有意义，我的另一个App是全部进入浏览器观看的。

**Comment by aunight** [comment]
https://v.anime1.me/watch?v=NIzi6
點選後會直接跳轉到瀏覽器內播放
並不會像新番一樣在APP 中播就不用調整手機轉向的問題

**Comment by HenryQuan** [comment]
我可以看看但是不一定可以。

**Comment by HenryQuan** [comment]
我想到了一个解决方案，晚上我会尝试一下。

**Comment by HenryQuan** [comment]
![image](https://user-images.githubusercontent.com/6754708/69206623-47c5b180-0ba1-11ea-8983-e300796433da.png)
在APP里面打开网页，然后在强制横屏，这样可以么？

**Comment by aunight** [comment]
從更新新番裡看的效果就是這樣的沒錯

**Comment by aunight** [comment]
感謝大大更新

**Comment by HenryQuan** [comment]
播放器确实是不同的，获得不了视频链接的话，就无法使用app的播放器。之后我还会改进一下。

**Comment by HenryQuan** [comment]
@aunight 目前已經都可以全屏播放了。内置播放器和瀏覽器的體驗應該會很接近了。十分感謝這個提議因爲APP的使用體驗確實會比以前好很多。這項功能會在1.0.6版本中加入。
