### ISSUE TITLE
Better TV support ?

### ISSUE THREAD

**Issue by tyfu86** [HenryQuan/AnimeOne#3]
Would you like to have a better tablet support?

**Comment by HenryQuan** [comment]
I think it should work on TV or tablet.

**Comment by tyfu86** [comment]
Thx for your reply, it can install on Android TV, but it cannot use the tv remote to control.

**Comment by HenryQuan** [comment]
I see but I wonder if Flutter actually supports Android TV. Thx for your reply. I might do some research first.

**Comment by HenryQuan** [comment]
@tyfu86 I have done some research. Unfortunately, Flutter doesn't support tv remote yet. However, it might be supported in the future but probably not anytime soon. I will close this issue for now.
