### ISSUE TITLE
希望可以增加收藏、歷史等功能

### ISSUE THREAD

**Issue by aunight** [HenryQuan/AnimeOne#4]
希望可以有收藏動漫及觀看歷史搜尋歷史的功能(或是能有記憶觀看暫停時間點的功能就像B站那樣，雖然感覺有點難)
另外小建議希望能將原本網頁版的倒序方式的影片可以變成正序
小Bug說明:如果在全屏播放時有彈出式的視窗彈出(例如:Messenger通訊軟體的泡泡球)
會導致全屏的狀態列不會再度隱藏
另外一提最新動畫區的動畫播放仍有兩種播放器形式一種是網頁的可以倒轉
另一種是只有播放鍵跟時間條的
希望可以統一一下
最後目前APP的使用體驗已經越來越好了
感謝作者了~

**Comment by HenryQuan** [comment]
播放器有兩個，我也在想要不要直接用網頁，這樣其實會簡單很多。內置瀏覽器其實還是很複雜的。
收藏和觀看歷史，我其實在考慮要不要增加。現在的想法是可以給看過的集數打勾。實現的想法是有的，但是暫時應該不會寫吧。
關於Messenger那個，我真的是不知道怎麼搞。確實是不會隱藏但是也不知道是否可以修復。
倒敘變成正序是可以的，但是這樣是不符合網站的設計。如果有20集以上的話，就比較麻煩（需要往上翻頁，一般是往下）

**Comment by aunight** [comment]
順序問題本身網頁設計的邏輯就很奇怪了
今天在看影片時都忘了看到第幾集
看看能不能影片上方顯示標題 或許就能代替
播放方面看你覺得吧跟方便修正我覺都兩個都不錯

**Comment by HenryQuan** [comment]
网页设计的逻辑应该是 追番 为主。所以新的在前面，旧的在后面。播放的话，我觉得现在这个样子也挺好的，有一个问题就是不统一。
十分感谢所有的建议。

**Comment by aunight** [comment]
好的沒問題感謝
