### ISSUE TITLE
增加需要輸入密碼觀看的影片

### ISSUE THREAD

**Issue by aunight** [HenryQuan/AnimeOne#6]
如題需要網站密碼的影片目前都無法觀看，希望可以改善感謝!

**Comment by HenryQuan** [comment]
之前遇到過這個問題，但是好像不是一直會有密碼。那個密碼是什麼呢。

**Comment by aunight** [comment]
對啊哈哈第一個A要大寫這樣

**Comment by aunight** [comment]
有些特殊的片源會用到密碼 像本季的某個新番就是

**Comment by HenryQuan** [comment]
可以发一个链接给我么

**Comment by aunight** [comment]
現在好像都沒有了但不排除以後會有 某些新出的劇場版動畫或是有年齡限制的動畫會有

**Comment by HenryQuan** [comment]
我看到过但是没有记录下来等之后再看到了可以研究一下。

**Comment by splitline** [comment]
基本上是動畫瘋 https://ani.gamer.com.tw/ 有上架的都會有密碼
像是這季的小圓就有擋 https://anime1.me/category/2020%e5%b9%b4%e5%86%ac%e5%ad%a3/%e9%ad%94%e6%b3%95%e7%b4%80%e9%8c%84-%e9%ad%94%e6%b3%95%e5%b0%91%e5%a5%b3%e5%b0%8f%e5%9c%93%e5%a4%96%e5%82%b3

**Comment by HenryQuan** [comment]
我這裏還是不需要任何密碼

**Comment by HenryQuan** [comment]
@splitline @aunight 看起來是會檢查IP地址的，不過我现在已经可以重現，應該也会加入到App裡面。

**Comment by aunight** [comment]
不只 原本剛出的青春豬頭劇場 B站的就有鎖
之前的異世界風俗娘也有鎖 好像也是巴哈片源 動畫瘋也有些像是映像研就不用密碼

**Comment by HenryQuan** [comment]
不過輸入密碼之後，一段時間之內應該是不需要再次輸入的吧。

**Comment by HenryQuan** [comment]
@aunight 剛剛更新了新版本，不知道有沒有解決密碼問題。

**Comment by aunight** [comment]
好的 感謝

**Comment by HenryQuan** [comment]
那我先把這個問題關閉了
