### ISSUE TITLE
Download videos with FFmpeg

### ISSUE THREAD

**Issue by HenryQuan** [HenryQuan/AnimeOne#7]
This is a request from my friend (he asked me to make this app in the first place).

Now, with the power of native android. I don't think it is impossible to do it. I will do some research and implement this feature in the future.

- [ ] Setup FFmpeg on Android Studio
- [ ] Try downloading mp3 and m3u8 format videos
- [ ] Set download path inside settings

**Comment by aunight** [comment]
下載這方面可以參考TubeMate App是可以直接下載的

**Comment by HenryQuan** [comment]
好的 多謝
