### ISSUE TITLE
網頁版更新會偵測瀏覽器導致APP跟PC版無法正常讀取

### ISSUE THREAD

**Issue by aunight** [HenryQuan/AnimeOne#9]
如題 希望可以修正
然後其實emina-one的功能已經符合我大部分的需求
我覺得希望你們可以合作成一個APP 融合兩邊的優點這樣

**Comment by HenryQuan** [comment]
目前還在修復，代碼已經寫好了但是並沒有成功（偶爾可以）。emina-one使用別的開發框架所以我們沒有辦法一起開發而且軟件的底層設計也不太相同。歷史記錄、書籤等功能其實不沒有很難，我比較懶所以還沒有開發（一天應該就可以些出來）。 可能是因為最近我使用AnimeGo更多一點，之後有時間會步入1.1.0版本的。

**Comment by aunight** [comment]
好的 感謝 辛苦了 但是他的播放器 動畫等還是不錯的

**Comment by HenryQuan** [comment]
他的播放器是自己写的所以特别棒。我觉得很多地方是比animeone要好很多的。

**Comment by aunight** [comment]
但是讀取速度慢你的很多啊
